### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by jorivanee** [InventivetalentDev/MapMenus#1]
Hey, it isnt working to me, it generates the folder, but it doesn't work ingame -_-

**Comment by InventivetalentDev** [comment]
Sorry, I forgot to update the issue template. Please provide all the information asked for in [**this file**](https://github.com/InventivetalentDev/MapMenus/blob/master/ISSUE_TEMPLATE.md) (Or create a new issue), as 'it isn't working' only tells me that you probably forgot to install the dependencies.

**Comment by jorivanee** [comment]
What are the dependencies?

**Comment by InventivetalentDev** [comment]
Apparently I forgot to list them in the description, sorry about that. You need to install [MapManager](https://www.spigotmc.org/resources/api-mapmanager-1-7-1-8-1-9.19198/). (And of course PacketListenerAPI, since MapManager depends on that)

**Comment by jorivanee** [comment]
Okay :dancer:
